import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function Test() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div>
        test
      </div>
    </main>
  );
}
